skip pre-commit

diff --git a/.github/workflows/precommit.yml b/.github/workflows/precommit.yml
--- a/.github/workflows/precommit.yml
+++ b/.github/workflows/precommit.yml
@@ -11,44 +11,44 @@ jobs:
       - name: Skip pre-commit
         run: exit 0
 
-      - uses: actions/checkout@v4
-        # some pre-commit hooks might need full history
-        with:
-          fetch-depth: 0
+      # - uses: actions/checkout@v4
+      #   # some pre-commit hooks might need full history
+      #   with:
+      #     fetch-depth: 0
 
-      - name: Set up
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.10"
+      # - name: Set up
+      #   uses: actions/setup-python@v4
+      #   with:
+      #     python-version: "3.10"
 
-      - name: Install
-        shell: bash
-        run: |
-          pip install pre-commit -q --root-user-action=ignore
-          pre-commit autoupdate
+      # - name: Install
+      #   shell: bash
+      #   run: |
+      #     pip install pre-commit -q --root-user-action=ignore
+      #     pre-commit autoupdate
 
-        # This step will fail if pre-commit exits non-zero for *any* reason
-      - name: Run Pre-Commit
-        run: |
-          success=false
-          for i in {1..5}; do
-            echo "Running pre-commit attempt $i..."
-            if pre-commit run --all-files --show-diff-on-failure; then
-              echo "Pre-commit checks passed"
-              success=true
-              break
-            else
-              exit_code=$?
-              echo "Attempt $i failed with exit code $exit_code."
-              if [ $i -lt 5 ]; then
-                sleep 5
-              fi
-            fi
-          done
+      #   # This step will fail if pre-commit exits non-zero for *any* reason
+      # - name: Run Pre-Commit
+      #   run: |
+      #     success=false
+      #     for i in {1..5}; do
+      #       echo "Running pre-commit attempt $i..."
+      #       if pre-commit run --all-files --show-diff-on-failure; then
+      #         echo "Pre-commit checks passed"
+      #         success=true
+      #         break
+      #       else
+      #         exit_code=$?
+      #         echo "Attempt $i failed with exit code $exit_code."
+      #         if [ $i -lt 5 ]; then
+      #           sleep 5
+      #         fi
+      #       fi
+      #     done
 
-          if [ "$success" = false ]; then
-            echo "Pre-commit failed"
-            exit 1
-          fi
-          echo "Pre-commit finished successfully."
-        shell: bash
+      #     if [ "$success" = false ]; then
+      #       echo "Pre-commit failed"
+      #       exit 1
+      #     fi
+      #     echo "Pre-commit finished successfully."
+      #   shell: bash
